//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using RoutingServer.ProxyCacheServiceReference;

namespace RoutingServer.ProxyCacheServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCacheServiceReference.IProxyCacheService")]
    public interface IProxyCacheService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetAvailableContracts", ReplyAction="http://tempuri.org/IProxyCacheService/GetAvailableContractsResponse")]
        SharedModels.BikeContract[] GetAvailableContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetAvailableContracts", ReplyAction="http://tempuri.org/IProxyCacheService/GetAvailableContractsResponse")]
        System.Threading.Tasks.Task<SharedModels.BikeContract[]> GetAvailableContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStationsByContract", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsByContractResponse")]
        SharedModels.BikeStation[] GetStationsByContract(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStationsByContract", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsByContractResponse")]
        System.Threading.Tasks.Task<SharedModels.BikeStation[]> GetStationsByContractAsync(string contractName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyCacheServiceChannel : IProxyCacheService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyCacheServiceClient : System.ServiceModel.ClientBase<IProxyCacheService>, IProxyCacheService {
        
        public ProxyCacheServiceClient() {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SharedModels.BikeContract[] GetAvailableContracts() {
            return base.Channel.GetAvailableContracts();
        }
        
        public System.Threading.Tasks.Task<SharedModels.BikeContract[]> GetAvailableContractsAsync() {
            return base.Channel.GetAvailableContractsAsync();
        }
        
        public SharedModels.BikeStation[] GetStationsByContract(string contractName) {
            return base.Channel.GetStationsByContract(contractName);
        }
        
        public System.Threading.Tasks.Task<SharedModels.BikeStation[]> GetStationsByContractAsync(string contractName) {
            return base.Channel.GetStationsByContractAsync(contractName);
        }
    }
}
