//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServer.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IProxyCacheService")]
    public interface IProxyCacheService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetAvailableContracts", ReplyAction="http://tempuri.org/IProxyCacheService/GetAvailableContractsResponse")]
        SharedModels.BikeContract[] GetAvailableContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetAvailableContracts", ReplyAction="http://tempuri.org/IProxyCacheService/GetAvailableContractsResponse")]
        System.Threading.Tasks.Task<SharedModels.BikeContract[]> GetAvailableContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStationsByContract", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsByContractResponse")]
        SharedModels.BikeStation[] GetStationsByContract(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStationsByContract", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsByContractResponse")]
        System.Threading.Tasks.Task<SharedModels.BikeStation[]> GetStationsByContractAsync(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/ComputeRoute", ReplyAction="http://tempuri.org/IProxyCacheService/ComputeRouteResponse")]
        string ComputeRoute(double startLatitude, double startLongitude, double endLatitude, double endLongitude, bool isBike);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/ComputeRoute", ReplyAction="http://tempuri.org/IProxyCacheService/ComputeRouteResponse")]
        System.Threading.Tasks.Task<string> ComputeRouteAsync(double startLatitude, double startLongitude, double endLatitude, double endLongitude, bool isBike);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/CallORS", ReplyAction="http://tempuri.org/IProxyCacheService/CallORSResponse")]
        string CallORS(string profile, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/CallORS", ReplyAction="http://tempuri.org/IProxyCacheService/CallORSResponse")]
        System.Threading.Tasks.Task<string> CallORSAsync(string profile, string start, string end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyCacheServiceChannel : RoutingServer.ServiceReference2.IProxyCacheService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyCacheServiceClient : System.ServiceModel.ClientBase<RoutingServer.ServiceReference2.IProxyCacheService>, RoutingServer.ServiceReference2.IProxyCacheService {
        
        public ProxyCacheServiceClient() {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SharedModels.BikeContract[] GetAvailableContracts() {
            return base.Channel.GetAvailableContracts();
        }
        
        public System.Threading.Tasks.Task<SharedModels.BikeContract[]> GetAvailableContractsAsync() {
            return base.Channel.GetAvailableContractsAsync();
        }
        
        public SharedModels.BikeStation[] GetStationsByContract(string contractName) {
            return base.Channel.GetStationsByContract(contractName);
        }
        
        public System.Threading.Tasks.Task<SharedModels.BikeStation[]> GetStationsByContractAsync(string contractName) {
            return base.Channel.GetStationsByContractAsync(contractName);
        }
        
        public string ComputeRoute(double startLatitude, double startLongitude, double endLatitude, double endLongitude, bool isBike) {
            return base.Channel.ComputeRoute(startLatitude, startLongitude, endLatitude, endLongitude, isBike);
        }
        
        public System.Threading.Tasks.Task<string> ComputeRouteAsync(double startLatitude, double startLongitude, double endLatitude, double endLongitude, bool isBike) {
            return base.Channel.ComputeRouteAsync(startLatitude, startLongitude, endLatitude, endLongitude, isBike);
        }
        
        public string CallORS(string profile, string start, string end) {
            return base.Channel.CallORS(profile, start, end);
        }
        
        public System.Threading.Tasks.Task<string> CallORSAsync(string profile, string start, string end) {
            return base.Channel.CallORSAsync(profile, start, end);
        }
    }
}
